name: Lista dos commits - PROD

on:
  push:
    branches:
      - main

jobs:
  prod-list-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Entrou na lista
        run: |
          git fetch --unshallow || true
          git log --pretty=format:"%H - %an <%ae> - %s - %ad"