name: PROD-DEPLOY

on:
  push:
    branches: [main]
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    # runs-on:
    #   group: Default
    #   labels: [self-hosted,Linux,x64,PROD]
    environment:
      name: production
      # url: 'https://nestjs-boilerplate.anjunexpress.com.br/' //
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Create env file'
        run: |
          echo '${{ secrets.PROD_ENV_FILE }}' > .env

      - name: install yarn
        run: npm i -g yarn

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: prisma generate
        run: yarn gen

#      - name: prisma migrate
#        run: yarn prisma migrate deploy

      - name: build
        run: yarn build
    
      - name: pm2 install
        run: npm install pm2 -g

      - name: start or reload server
        run: pm2 startOrGracefulReload ecosystem.config.js
